channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.4
  - torchaudio
  - tensorboard
  - matplotlib
  - pandas
  - pytest
  - git-lfs
  - pip:
    - diffsptk
    - pyworld
    - tqdm
    - ipdb
